<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>TL.TransportLogistics.Tariffs.Business.Aggregates</RootNamespace>
        <AssemblyName>TL.TransportLogistics.Tariffs.Business.Aggregates</AssemblyName>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\SharedKernel\Business\SharedKernel.Aggregates\SharedKernel.Aggregates.csproj" />
    </ItemGroup>

</Project>
