<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>TL.TransportLogistics.Tariffs.Startups.WebApi</RootNamespace>
    <AssemblyName>TL.TransportLogistics.Tariffs.Startups.WebApi</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hellang.Middleware.ProblemDetails" Version="6.5.1"/>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\SharedKernel\Infrastructure\SharedKernel.AspNet\SharedKernel.AspNet.csproj"/>
    <ProjectReference Include="..\..\..\..\SharedKernel\Infrastructure\SharedKernel.JsonSerializer.Extensions\SharedKernel.JsonSerializer.Extensions.csproj"/>
    <ProjectReference Include="..\..\..\..\SharedKernel\System\SharedKernel.System.ComponentModel\SharedKernel.System.ComponentModel.csproj"/>
    <ProjectReference Include="..\..\Application\Tariffs.UseCases\Tariffs.UseCases.csproj"/>
    <ProjectReference Include="..\..\Domain\Tariff.Aggregates\Tariff.Aggregates.csproj"/>
    <ProjectReference Include="..\Tariffs.DependencyInjection\Tariffs.DependencyInjection.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controllers\Tariff\Dto\RouteDto.cs">
      <DependentUpon>SaveTariffRouteRequest.cs</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
