<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>TL.SharedKernel.Business.Aggregates</RootNamespace>
        <AssemblyName>TL.SharedKernel.Business.Aggregates</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\System\SharedKernel.System.ComponentModel\SharedKernel.System.ComponentModel.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="InvalidValue.cs">
            <DependentUpon>Error.cs</DependentUpon>
        </Compile>
        <Compile Update="NotFound.cs">
            <DependentUpon>Error.cs</DependentUpon>
        </Compile>
        <Compile Update="InvalidParameters.cs">
            <DependentUpon>Error.cs</DependentUpon>
        </Compile>
        <Compile Update="Thrower.cs">
            <DependentUpon>Error.cs</DependentUpon>
        </Compile>
        <Compile Update="Error.cs">
            <DependentUpon>ErrorException.cs</DependentUpon>
        </Compile>
        <Compile Update="Conflict.cs">
            <DependentUpon>Error.cs</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
