<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>TL.SharedKernel.Infrastructure.Compress.Extensions</RootNamespace>
        <AssemblyName>TL.SharedKernel.Infrastructure.Compress.Extensions</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.IO.Compression" Version="4.3.0"/>
    </ItemGroup>

</Project>
