<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>TL.SharedKernel.Application.Commands</RootNamespace>
        <AssemblyName>TL.SharedKernel.Application.Commands</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <Compile Update="IUseCase.cs">
            <DependentUpon>IUseCaseHandler.cs</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
