<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TL.SharedKernel.Application.Commands</RootNamespace>
    <AssemblyName>TL.SharedKernel.Application.Commands</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Business\SharedKernel.Aggregates\SharedKernel.Aggregates.csproj"/>
  </ItemGroup>

</Project>
